/**
 * AerienDemandeFretPage — "Confier mon fret aérien"
 * Creates a freight_request with freight_mode='air'
 * Matching to Air Shipping Partners + Independents
 */
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Plane, ArrowLeft, Package, MapPin, Scale, Shield, Zap } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";

const INCOTERMS = ["EXW", "FOB", "CIF", "DDP", "DAP", "FCA", "CPT", "CIP"];

export default function AerienDemandeFretPage() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [userId, setUserId] = useState<string | null>(null);

  const [form, setForm] = useState({
    originCountry: "France",
    originCity: "",
    originAirport: "",
    destinationCountry: "Sénégal",
    destinationCity: "",
    destinationAirport: "",
    merchandiseType: "",
    merchandiseDescription: "",
    weightKg: "",
    volumeM3: "",
    dimensionsCm: "",
    declaredValue: "",
    currency: "EUR",
    incoterm: "",
    customsRequired: false,
    insuranceRequired: false,
    isFragile: false,
    isUrgent: false,
    urgencyLevel: "standard",
    finalDeliveryMode: "pickup",
    pickupDateFrom: "",
    pickupDateTo: "",
    notes: "",
  });

  useEffect(() => {
    (async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) { navigate("/auth"); return; }
      setUserId(user.id);
    })();
  }, []);

  const handleSubmit = async () => {
    if (!userId) return;
    if (!form.originCity || !form.destinationCity || !form.merchandiseType) {
      toast({ title: "Champs requis manquants", variant: "destructive" });
      return;
    }

    setLoading(true);
    try {
      const { error } = await supabase.from("freight_requests").insert({
        client_id: userId,
        freight_mode: "air",
        request_number: "TEMP", // auto-generated by trigger
        origin_country: form.originCountry,
        origin_city: form.originCity,
        origin_port_or_airport: form.originAirport || null,
        destination_country: form.destinationCountry,
        destination_city: form.destinationCity,
        destination_port_or_airport: form.destinationAirport || null,
        merchandise_type: form.merchandiseType,
        merchandise_description: form.merchandiseDescription || null,
        weight_kg: form.weightKg ? parseFloat(form.weightKg) : 0,
        volume_m3: form.volumeM3 ? parseFloat(form.volumeM3) : 0,
        dimensions_cm: form.dimensionsCm || null,
        declared_value: form.declaredValue ? parseFloat(form.declaredValue) : 0,
        currency: form.currency,
        incoterm: form.incoterm || null,
        customs_required: form.customsRequired,
        insurance_required: form.insuranceRequired,
        is_fragile: form.isFragile,
        is_urgent: form.isUrgent,
        urgency_level: form.urgencyLevel,
        final_delivery_mode: form.finalDeliveryMode,
        pickup_date_from: form.pickupDateFrom || null,
        pickup_date_to: form.pickupDateTo || null,
        notes: form.notes || null,
      });

      if (error) throw error;
      toast({ title: "Demande envoyée ✓", description: "Les transporteurs aériens vont vous proposer des offres." });
      navigate("/aerien/demande");
    } catch (err: any) {
      toast({ title: "Erreur", description: err.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const update = (key: string, value: any) => setForm(f => ({ ...f, [key]: value }));

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-primary shadow-lg" style={{ paddingTop: 'calc(8px + var(--safe-top, 0px))' }}>
        <div className="px-3 py-2.5 flex items-center gap-3">
          <Button variant="ghost" size="icon" className="text-white h-8 w-8" onClick={() => navigate(-1)}>
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div className="flex items-center gap-2">
            <Plane className="w-5 h-5 text-white" />
            <h1 className="text-white font-bold text-sm">Confier mon fret aérien</h1>
          </div>
        </div>
      </header>

      <div className="px-4 py-4 space-y-4 pb-24 max-w-lg mx-auto">
        {/* Origin */}
        <Card>
          <CardContent className="p-3 space-y-3">
            <h3 className="text-xs font-bold flex items-center gap-1.5">
              <MapPin className="w-3.5 h-3.5 text-primary" /> Origine
            </h3>
            <div className="grid grid-cols-2 gap-2">
              <div>
                <Label className="text-[10px]">Pays</Label>
                <Input className="h-8 text-xs" value={form.originCountry} onChange={e => update("originCountry", e.target.value)} />
              </div>
              <div>
                <Label className="text-[10px]">Ville</Label>
                <Input className="h-8 text-xs" placeholder="Paris" value={form.originCity} onChange={e => update("originCity", e.target.value)} />
              </div>
              <div className="col-span-2">
                <Label className="text-[10px]">Aéroport (optionnel)</Label>
                <Input className="h-8 text-xs" placeholder="CDG" value={form.originAirport} onChange={e => update("originAirport", e.target.value)} />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Destination */}
        <Card>
          <CardContent className="p-3 space-y-3">
            <h3 className="text-xs font-bold flex items-center gap-1.5">
              <MapPin className="w-3.5 h-3.5 text-primary" /> Destination
            </h3>
            <div className="grid grid-cols-2 gap-2">
              <div>
                <Label className="text-[10px]">Pays</Label>
                <Input className="h-8 text-xs" value={form.destinationCountry} onChange={e => update("destinationCountry", e.target.value)} />
              </div>
              <div>
                <Label className="text-[10px]">Ville</Label>
                <Input className="h-8 text-xs" placeholder="Dakar" value={form.destinationCity} onChange={e => update("destinationCity", e.target.value)} />
              </div>
              <div className="col-span-2">
                <Label className="text-[10px]">Aéroport (optionnel)</Label>
                <Input className="h-8 text-xs" placeholder="DSS" value={form.destinationAirport} onChange={e => update("destinationAirport", e.target.value)} />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Cargo Details */}
        <Card>
          <CardContent className="p-3 space-y-3">
            <h3 className="text-xs font-bold flex items-center gap-1.5">
              <Package className="w-3.5 h-3.5 text-primary" /> Marchandise
            </h3>
            <div>
              <Label className="text-[10px]">Type de marchandise *</Label>
              <Input className="h-8 text-xs" placeholder="Électronique, textile, pièces auto..." value={form.merchandiseType} onChange={e => update("merchandiseType", e.target.value)} />
            </div>
            <div>
              <Label className="text-[10px]">Description détaillée</Label>
              <Textarea className="text-xs min-h-[50px]" placeholder="Détails sur la marchandise..." value={form.merchandiseDescription} onChange={e => update("merchandiseDescription", e.target.value)} />
            </div>
            <div className="grid grid-cols-3 gap-2">
              <div>
                <Label className="text-[10px]">Poids (kg)</Label>
                <Input type="number" className="h-8 text-xs" placeholder="100" value={form.weightKg} onChange={e => update("weightKg", e.target.value)} />
              </div>
              <div>
                <Label className="text-[10px]">Volume (m³)</Label>
                <Input type="number" className="h-8 text-xs" placeholder="2" value={form.volumeM3} onChange={e => update("volumeM3", e.target.value)} />
              </div>
              <div>
                <Label className="text-[10px]">Dimensions</Label>
                <Input className="h-8 text-xs" placeholder="LxlxH" value={form.dimensionsCm} onChange={e => update("dimensionsCm", e.target.value)} />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div>
                <Label className="text-[10px]">Valeur déclarée</Label>
                <Input type="number" className="h-8 text-xs" placeholder="5000" value={form.declaredValue} onChange={e => update("declaredValue", e.target.value)} />
              </div>
              <div>
                <Label className="text-[10px]">Incoterm</Label>
                <Select value={form.incoterm} onValueChange={v => update("incoterm", v)}>
                  <SelectTrigger className="h-8 text-xs"><SelectValue placeholder="Choisir" /></SelectTrigger>
                  <SelectContent>
                    {INCOTERMS.map(i => <SelectItem key={i} value={i} className="text-xs">{i}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Options */}
        <Card>
          <CardContent className="p-3 space-y-3">
            <h3 className="text-xs font-bold flex items-center gap-1.5">
              <Shield className="w-3.5 h-3.5 text-primary" /> Options
            </h3>
            <div className="space-y-2">
              {[
                { key: "customsRequired", label: "Dedouanement requis", icon: "" },
                { key: "insuranceRequired", label: "Assurance fret", icon: "" },
                { key: "isFragile", label: "Marchandise fragile", icon: "" },
                { key: "isUrgent", label: "Envoi urgent", icon: "" },
              ].map(opt => (
                <div key={opt.key} className="flex items-center justify-between">
                  <span className="text-xs flex items-center gap-1.5">{opt.icon} {opt.label}</span>
                  <Switch checked={(form as any)[opt.key]} onCheckedChange={v => update(opt.key, v)} />
                </div>
              ))}
            </div>

            {form.isUrgent && (
              <div>
                <Label className="text-[10px]">Niveau d'urgence</Label>
                <Select value={form.urgencyLevel} onValueChange={v => update("urgencyLevel", v)}>
                  <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="standard" className="text-xs">Standard</SelectItem>
                    <SelectItem value="express" className="text-xs">Express (48-72h)</SelectItem>
                    <SelectItem value="critical" className="text-xs">Critique (24h)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}

            <div>
              <Label className="text-[10px]">Livraison finale</Label>
              <Select value={form.finalDeliveryMode} onValueChange={v => update("finalDeliveryMode", v)}>
                <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="pickup" className="text-xs">Retrait aéroport</SelectItem>
                  <SelectItem value="hub" className="text-xs">Dépôt hub Konnekt</SelectItem>
                  <SelectItem value="road" className="text-xs">Livraison routière finale</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Dates */}
        <Card>
          <CardContent className="p-3 space-y-2">
            <h3 className="text-xs font-bold">📅 Dates souhaitées</h3>
            <div className="grid grid-cols-2 gap-2">
              <div>
                <Label className="text-[10px]">À partir du</Label>
                <Input type="date" className="h-8 text-xs" value={form.pickupDateFrom} onChange={e => update("pickupDateFrom", e.target.value)} />
              </div>
              <div>
                <Label className="text-[10px]">Jusqu'au</Label>
                <Input type="date" className="h-8 text-xs" value={form.pickupDateTo} onChange={e => update("pickupDateTo", e.target.value)} />
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Notes */}
        <Card>
          <CardContent className="p-3 space-y-2">
            <Label className="text-[10px]">Notes complémentaires</Label>
            <Textarea className="text-xs min-h-[50px]" placeholder="Informations supplémentaires..." value={form.notes} onChange={e => update("notes", e.target.value)} />
          </CardContent>
        </Card>

        <Button className="w-full h-10" onClick={handleSubmit} disabled={loading}>
          {loading ? "Envoi en cours..." : "Envoyer ma demande de fret"}
        </Button>

        <p className="text-[10px] text-muted-foreground text-center">
          💡 Les transporteurs aériens qualifiés recevront votre demande et vous proposeront des offres.
        </p>
      </div>
    </div>
  );
}
